# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerSelector
                                 A QGIS plugin
 Select layers for  Polygon Linker
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-19
        copyright            : (C) 2020 by Rob Zeeman, KNAW Humanities Cluster
        email                : rob.zeeman@di.huc.knaw.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerSelector class from file LayerSelector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_selector import LayerSelector
    return LayerSelector(iface)
